version: '3'

services:
  app:
    image: v2fly/v2fly-core
    ports:
      - 1080:1080
    restart: always 
    volumes:
      - ./config.json:/etc/v2ray/config.json
    command: run -config=/etc/v2ray/config.json