version: "3"
services:
  cloudreve:
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    ports:
      - 5212:5212
  v2ray:
    image: v2fly/v2fly-core
    ports:
      - 127.0.0.1:23333:23333
    restart: unless-stopped 
    volumes:
      - ./config.json:/etc/v2ray/config.json
    command: run -config=/etc/v2ray/config.json